language: java
jdk:
  - oraclejdk8

jobs:
  include:
      - stage: test
        script: ./gradlew --version
      - # stage name not required, will continue to use `test`
        script: ./gradlew tasks
      - stage: deploy
        script: echo "HELLO WORLD!"


after_success:
 - bash <(curl -s https://codecov.io/bash)
