language: java
jdk:
  - oraclejdk8

jobs:
  include:
      - stage: compile
      - stage: test
      - stage: execute script
        script:
          - ./gradlew --version
          - ./gradlew tasks
      - stage: deploy to dev
        script: echo "release to dev"
        deploy:
          provider: script
          script: echo "execute deploy.sh dev"
          on:
            branch: master
      - stage: deploy to stag
        script: echo "release to stag"
        deploy:
          provider: script
          script: echo "execute deploy.sh stag"
          on:
              all_branches: true
              condition: $TRAVIS_BRANCH =~ ^release|production$

after_success:
 - bash <(curl -s https://codecov.io/bash)
